"""Add role to user model

Revision ID: 017232b9cf6a
Revises: 9a5da2ca460b
Create Date: 2025-05-18 22:18:35.694307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017232b9cf6a'
down_revision = '9a5da2ca460b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
