"""Enable cascade delete on OrderItem.menu_item_id

Revision ID: 104fc5dd1911
Revises: 32aa3a064b4b
Create Date: 2025-05-26 22:59:41.044006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104fc5dd1911'
down_revision = '32aa3a064b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('order_item_menu_item_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'menu_item', ['menu_item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_item_menu_item_id_fkey', 'menu_item', ['menu_item_id'], ['id'])

    # ### end Alembic commands ###
