"""Add is_happy_hour_eligible to MenuItem

Revision ID: 14f84347091e
Revises: 104fc5dd1911
Create Date: 2025-05-28 18:10:32.156624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f84347091e'
down_revision = '104fc5dd1911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_happy_hour_eligible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_column('is_happy_hour_eligible')

    # ### end Alembic commands ###
