"""create offers table

Revision ID: 256bdee38cc3
Revises: 4d61ad1f36d7
Create Date: 2025-07-09 01:32:19.187154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256bdee38cc3'
down_revision = '4d61ad1f36d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('subtitle', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('bullets', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    # ### end Alembic commands ###
