"""Add ChatLog model

Revision ID: 304f8ed7da24
Revises: 43614f1d5363
Create Date: 2025-06-04 04:17:22.689495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304f8ed7da24'
down_revision = '43614f1d5363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_log')
    # ### end Alembic commands ###
