"""Create Offer table

Revision ID: 3fbf2016e0bd
Revises: 256bdee38cc3
Create Date: 2025-07-09 09:09:30.129170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fbf2016e0bd'
down_revision = '256bdee38cc3'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('offers') as batch_op:
        # (optional) bump image_url length
        batch_op.alter_column(
          'image_url',
          existing_type=sa.VARCHAR(length=300),
          type_=sa.String(length=500),
          existing_nullable=False,
          nullable=False,
        )

        # this line tells Postgres how to convert your old TEXT into JSONB
        batch_op.alter_column(
          'bullets',
          existing_type=sa.TEXT(),
          type_=postgresql.JSONB(),
          postgresql_using='bullets::jsonb',
          existing_nullable=False,
          nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        # revert bullets back to TEXT
        batch_op.alter_column(
            'bullets',
            existing_type=postgresql.JSONB(),
            type_=sa.TEXT(),
            existing_nullable=False,
            nullable=False
        )
        # revert image_url length
        batch_op.alter_column(
            'image_url',
            existing_type=sa.String(length=500),
            type_=sa.VARCHAR(length=300),
            existing_nullable=False,
            nullable=True  # or False if you want to keep NOT NULL
        )
    # ### end Alembic commands ###
