"""Add Coupon model

Revision ID: 43614f1d5363
Revises: 815c996c6f62
Create Date: 2025-06-03 21:13:53.976593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43614f1d5363'
down_revision = '815c996c6f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=256), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.Column('redeemed_by', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['redeemed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupon')
    # ### end Alembic commands ###
