"""Add VoucherRegistration and extend Coupon model

Revision ID: 4d61ad1f36d7
Revises: 304f8ed7da24
Create Date: 2025-06-15 20:33:52.053202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d61ad1f36d7'
down_revision = '304f8ed7da24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voucher_id', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('house_number', sa.String(length=20), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('county', sa.String(length=50), nullable=False),
    sa.Column('postcode', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voucher_id')
    )
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scanned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('middle_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('house_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('postcode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.drop_column('redeemed')
        batch_op.drop_column('redeemed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redeemed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('redeemed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
        batch_op.drop_column('country')
        batch_op.drop_column('postcode')
        batch_op.drop_column('county')
        batch_op.drop_column('city')
        batch_op.drop_column('street')
        batch_op.drop_column('house_number')
        batch_op.drop_column('dob')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('middle_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('scanned_at')

    op.drop_table('voucher_registration')
    # ### end Alembic commands ###
