"""Increase password hash length

Revision ID: 57749d5be8f1
Revises: 7ba7a92d1d74
Create Date: 2025-05-18 21:15:08.873761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57749d5be8f1'
down_revision = '7ba7a92d1d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
