"""Add started_at to OpenTab

Revision ID: 748a0d3aa3c3
Revises: b7a3736e1da5
Create Date: 2025-05-21 03:03:34.287764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '748a0d3aa3c3'
down_revision = 'b7a3736e1da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_tab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('opened_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_tab', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opened_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###
