"""Recreate happy hour rules

Revision ID: 815c996c6f62
Revises: 
Create Date: 2025-06-02 02:56:48.283459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '815c996c6f62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('happy_hour_promotion')
    with op.batch_alter_table('happy_hour_rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_description', sa.String(length=100), nullable=True))
        batch_op.alter_column('days_active',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('happy_hour_rule', schema=None) as batch_op:
        batch_op.alter_column('days_active',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('deal_description')

    op.create_table('happy_hour_promotion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('discount_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('discount_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('menu_item_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='happy_hour_promotion_pkey')
    )
    # ### end Alembic commands ###
