"""Add Booking model

Revision ID: 944db050ab33
Revises: 9ebce97fe170
Create Date: 2025-05-19 03:50:49.831984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944db050ab33'
down_revision = '9ebce97fe170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_number', sa.String(length=10), nullable=False),
    sa.Column('booking_time', sa.DateTime(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
