"""Add oasis_card_id to user

Revision ID: 9ebce97fe170
Revises: b6cb735230e3
Create Date: 2025-05-19 02:59:26.483071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebce97fe170'
down_revision = 'b6cb735230e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oasis_card_id', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['oasis_card_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('oasis_card_id')

    # ### end Alembic commands ###
