"""Add HappyHourRule model

Revision ID: fcd54ebf1522
Revises: 748a0d3aa3c3
Create Date: 2025-05-21 05:11:58.246679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd54ebf1522'
down_revision = '748a0d3aa3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('happy_hour_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('days_active', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('happy_hour_rule')
    # ### end Alembic commands ###
